version: "3.8"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/fast-chat
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # frontend:
  #   build:
  #     context: ./chat-app
  #     dockerfile: Dockerfile-frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

volumes:
  mongodb_data:
